### ISSUE TITLE
Feature Request: Gmail API

### ISSUE THREAD

**Issue by sleepyxuras91** [hashicorp/terraform-provider-googleworkspace#117]
Hi thanks for the great provider

A issue I'm having within a chairty domains I manage on Google Worksapce (previously Gapps for charity)  is to manage Gmail features, the things I would like to able to setup is Aliases in the "Send mail as" setting with ability to set a default as as a admin in the dashboard you can give people a Alias but doing the setup of the "Send mail as" means logging into their account/ or screensharing which is difficult for the audiance of people I am working with.

Seems this is covered within the Worksapce for developers help documenation 

https://developers.google.com/gmail/api/guides/alias_and_signature_settings

Other things are forwarding, vacation messages and other things that the user manage themselves. 

Not sure if this API is in scope as I've never actually done any API integrations myself with this Google API but have used a Trail of a dashboard which gave this support but became prehibitivly expensive for the charity to actually subscribe to it. 

Keep up the fantastic work.

(Watched the "Community Office Hours: Terraform" video)

**Comment by megan07** [comment]
Hi @sleepyxuras91! Thanks for the feature request - and for watching Community Office hours!
I believe this is the API you're looking for: https://developers.google.com/gmail/api/reference/rest/v1/users.settings.sendAs

We will give it a shot! Thanks!

**Comment by sleepyxuras91** [comment]
Yup that certainly looks a bit more detailed than the API I put in my inital issue. Thanks!

**Comment by appilon** [comment]
Hi @sleepyxuras91 we are actively working on this feature and have it working for internally created users within the same domain/admin workspace, however I imagine you are looking (as are many others) to add external to google send-as aliases. This requires that SMTP MSA is configured https://developers.google.com/gmail/api/reference/rest/v1/users.settings.sendAs#SendAs (see smtpMsa).

We have added these fields to the feature, but it will unfortunately go untested as it's impractical for us to set up that scenario in testing. Assuming one does manage to configure a working SMTP server for Google to reach out to, the workspace needs to enable SMTP relaying otherwise the following error occurs
```
 Error 400: Sending through alternate SMTP service is disallowed
 ```
 
Do you happen to already have all that setup? If so, it would be of great help to us if you could let us know if the external send as aliases works by filing a new issue(s).

**Comment by sleepyxuras91** [comment]
Hi @appilon sorry this isn't a use case we have either generally send-as alias' we're setting up are also just internal addresses to give more generic names to emails instead of having personally named emails on advertising so email doesn't get lost when people change roles / leave.
