### ISSUE TITLE
googleworkspace_group_settings Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by halradaideh** [hashicorp/terraform-provider-googleworkspace#130]
### Terraform Version
1.0.0

### Affected Resource(s)
- googleworkspace_group_settings

### Terraform Configuration Files
```hcl

provider "googleworkspace" {
  credentials = "X.json"
  impersonated_user_email = "X"
  oauth_scopes = [
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/admin.directory.user",
  ]
  customer_id = "X"
}


resource "googleworkspace_group" "X" {
  email         = "X"
  description   = "Managed by TF | X"
}

resource "googleworkspace_group_settings" "X" {
  email = googleworkspace_group.X.email

  allow_external_members = false

  who_can_join            = "INVITED_CAN_JOIN"
  who_can_view_membership = "ALL_MANAGERS_CAN_VIEW"
  who_can_post_message    = "ALL_MEMBERS_CAN_POST"
}
```

### Expected Behavior
to run

### Actual Behavior
Request had insufficient authentication scopes

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
BTW I can create groups and add members to groups using the service account

**Comment by megan07** [comment]
Hi @halradaideh ! Would you mind trying it with `https://www.googleapis.com/auth/apps.groups.settings` added to the list of scopes? The group settings is a separate API and has a separate scope. Let me know if that still doesn't work and I'll take a deeper look. Thanks!

**Comment by halradaideh** [comment]
yup worked, please modify documentation :D

**Comment by sajid-khan-js** [comment]
@halradaideh @megan07 

Even with the additional scope I'm still getting:

```hcl
googleworkspace_group_settings.settings: Creating...
╷
│ Error: googleapi: Error 403: Request had insufficient authentication scopes.
│ More details:
│ Reason: insufficientPermissions, Message: Insufficient Permission
│ 
│ 
│   with googleworkspace_group_settings.settings,
│   on main.tf line 11, in resource "googleworkspace_group_settings" "settings":
│   11: resource "googleworkspace_group_settings" "settings" {
│ 
```

My config:

```hcl
provider "googleworkspace" {
  customer_id             = "X"
  oauth_scopes = [
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/admin.directory.user",
    "https://www.googleapis.com/auth/apps.groups.settings"
  ]
}

resource "googleworkspace_group_settings" "settings" {
  email = "X@X.com"

  allow_external_members = true
}
```

I've authenticated with my superadmin account like so: `gcloud auth login --update-adc`

## Service account

I've omitted the use of a GCP service account for now, but if add one to `impersonated_user_email` e.g. `terraform-pipeline@my-tf-project.iam.gserviceaccount.com`, and give it a suitable admin role e.g. `Groups Editor`, could that work if said operation was running inside GCP (CloudBuild)?

#127 seems to suggest this isn't feasible right now.

**Comment by halradaideh** [comment]
@sajid-khan-js did you added it to workspace deligation client scopes?

**Comment by sajid-khan-js** [comment]
Ended up actually reading the docs 😆 and noticed this: https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs#authentication

I have mentioned to get it working by using the domain wide delegation method.

@megan07 is there any planned support for https://workspaceupdates.googleblog.com/2020/08/use-service-accounts-google-groups-without-domain-wide-delegation.html in the provider?

Thanks

**Comment by sajid-khan-js** [comment]
## No domain wide delegation required :) 

Just to update the thread, I did get this working with a service account without having setup domain wide delegation (as per the release notes [here](https://workspaceupdates.googleblog.com/2020/08/use-service-accounts-google-groups-without-domain-wide-delegation.html)).

Essentially: `admin.google.com` > Admin roles > Groups Editor > Assign service accounts

This simplifies the provider config, as you don't need to worry about scopes or even impersonating a user since the service account has direct access to the Workspace API.

```hcl
provider "googleworkspace" {
  credentials  = "my_sa.json"
  customer_id  = "X"
}

resource "googleworkspace_group_settings" "settings" {
  email = "testing@X.com"

  allow_external_members = true
  ....
}

```

Someone had a similar outcome with the old provider too: https://github.com/DeviaVir/terraform-provider-gsuite/pull/156#issuecomment-788750237

## Application default credentials

The last thing I want to understand more is whether I can use this provider without a static service account key. We discourage the use of them (as do Google in whitepapers and docs), and in fact we block the creation of service account keys for the majority of our GCP projects [using an GCP org policy](https://cloud.google.com/resource-manager/docs/organization-policy/restricting-service-accounts#disable_service_account_key_creation)

So, ideally, I want to be able to interact with the provider via application default credentials. This allows an authenticated human running terraform locally to user this provider, and will allow a GCP resource which has a service account assigned e.g., `Cloud Build` to run this provider without a static service account key.

[This comment](https://github.com/DeviaVir/terraform-provider-gsuite/issues/168#issuecomment-857380778) gives a working method for a human user and I got it working with this provider, but it requires an interactive login, any ideas on how to use this with short-lived credentials inside a GCP environment e.g., Cloud Build?

Thanks

**Comment by megan07** [comment]
Hi all! I have a PR open to fix the initial issue noted above (documentation for scopes). Feel free to open a new issue (or follow #127) for further requests. Thanks!

**Comment by antonhihealth** [comment]
as of Dec 2023, I can confirm what @sajidk1 said still works.
- remove scopes and impersonated user from google provider config
- assign service account to Groups Editor in G Admin
- save credentials json file of the said service account to the env var GOOGLEWORKSPACE_CREDENTIALS
- log into G CLI via `gcloud auth login`
- magic
