### ISSUE TITLE
Feature request: Allow using `GOOGLE_CREDENTIALS` environment variable

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform-provider-googleworkspace#87]
Thanks for releasing this! We're somewhat interested in exploring using this provider while we wait for some updates in the Cloud Identity APIs, but we noticed that it currently uses a different set of environment variables for credentials from the [google](https://github.com/hashicorp/terraform-provider-google) provider.

Is there any chance this provider could support the use of the `GOOGLE_CREDENTIALS` environment variable? Our Terraform Cloud workspaces are already configured with this environment variable, and doing so would allow us to use this provider with no further changes.

**Comment by ari-becker** [comment]
Adding onto this feature request, as somebody who would like to use this provider with Terraform Cloud, we'd like a simple way to drop the Google-provided credentials JSON into either a sensitive environment variable or a sensitive Terraform variable and have it just work.

Because the documentation says that the provider requires a filepath and not the contents of the file itself, this doesn't work so smoothly. I'm actually a little confused that the provider requires a filepath and not the contents; using the contents is much more flexible as Terraform provides a `file(path)` function to convert filepaths into their contents. As it is, it currently seems like we would need to use the `local` provider to take the credentials JSON from a Terraform variable, save it to a file, and then reference that file from the `googleworkspace` provider?
